name: CI Checks

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh && \
        curl https://sh.rustup.rs -sSf | sh && \
        cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
    - name: Env
      run: echo "Rust:$(rustc -V) $(cargo version)"
    - name: Lint
      run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
